repository: qwelyt/qwelyt.github.io
website: https://qwelyt.github.io
github_username: qwelyt

remote_theme: luxedo/jekyll-theme-potato-hacker

theme_base: "dark"
theme_switch: on
highlighter_theme: monokai
blog: on
toolbar_priority:
  - Home
  - Projects
  - Blog
collections:
  dropdown:
    output: true
